<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Admin" failures="0" tests="6" name="Default test" time="0.025" errors="0" timestamp="27 Sep 2022 07:29:03 GMT">
  <testcase classname="com.noncommerce.user.User_02_Login" name="@BeforeClass beforeClass" time="0.007">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.noncommerce.user.User_02_Login.beforeClass(User_02_Login.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass beforeClass -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="@AfterClass AfterClass" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass AfterClass -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_01_Empty_Data" time="0.0">
    <skipped/>
  </testcase> <!-- Log_01_Empty_Data -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_02_Invalid_Email" time="0.0">
    <skipped/>
  </testcase> <!-- Log_02_Invalid_Email -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_03_Unregistered_Email" time="0.0">
    <skipped/>
  </testcase> <!-- Log_03_Unregistered_Email -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_04_Registered_Email_Empty_Password" time="0.0">
    <skipped/>
  </testcase> <!-- Log_04_Registered_Email_Empty_Password -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_05_Registerred_Email_Invalid_Password" time="0.0">
    <skipped/>
  </testcase> <!-- Log_05_Registerred_Email_Invalid_Password -->
  <testcase classname="com.noncommerce.user.User_02_Login" name="Log_06_Login_Successful" time="0.0">
    <skipped/>
  </testcase> <!-- Log_06_Login_Successful -->
</testsuite> <!-- Default test -->
